// OpalDiagnostics.ErrorCode~OpalCrypto.swift

import OpalDiagnostics

extension OpalDiagnostics.ErrorCode {
    static let ambiguousLanguage = Self(rawValue: "ambiguous_language")
    static let cryptographyFailure = Self(rawValue: "cryptography_failure")
    static let derivedKeyLengthExceedsLimit = Self(rawValue: "derived_key_length_exceeds_limit")
    static let decodedDataExceedsMaximumByteCount = Self(
        rawValue: "decoded_data_exceeds_maximum_byte_count"
    )
    static let depthOverflow = Self(rawValue: "depth_overflow")
    static let emptyCommitmentList = Self(rawValue: "empty_commitment_list")
    static let emptySalt = Self(rawValue: "empty_salt")
    static let hardenedDerivationRequiresPrivateKey = Self(rawValue: "hardened_derivation_requires_private_key")
    static let insecureAlternateBasePoint = Self(rawValue: "insecure_alternate_base_point")
    static let invalidAlternateBasePoint = Self(rawValue: "invalid_alternate_base_point")
    static let invalidAlternateBasePointLength = Self(rawValue: "invalid_alternate_base_point_length")
    static let invalidAlternateBasePointPrefix = Self(rawValue: "invalid_alternate_base_point_prefix")
    static let invalidBase58 = Self(rawValue: "invalid_base58")
    static let invalidChainCodeLength = Self(rawValue: "invalid_chain_code_length")
    static let invalidCharacterFound = Self(rawValue: "invalid_character_found")
    static let invalidChecksum = Self(rawValue: "invalid_checksum")
    static let invalidCiphertext = Self(rawValue: "invalid_ciphertext")
    static let ciphertextByteCountExceedsMaximum = Self(rawValue: "ciphertext_byte_count_exceeds_maximum")
    static let ciphertextByteCountOverflow = Self(rawValue: "ciphertext_byte_count_overflow")
    static let invalidCommitment = Self(rawValue: "invalid_commitment")
    static let invalidCommitmentLength = Self(rawValue: "invalid_commitment_length")
    static let invalidCompressionMarker = Self(rawValue: "invalid_compression_marker")
    static let invalidDerivedKey = Self(rawValue: "invalid_derived_key")
    static let invalidDerivedKeyLength = Self(rawValue: "invalid_derived_key_length")
    static let invalidDepthMetadata = Self(rawValue: "invalid_depth_metadata")
    static let invalidDigestLength = Self(rawValue: "invalid_digest_length")
    static let invalidDER = Self(rawValue: "invalid_der")
    static let invalidEntropyLength = Self(rawValue: "invalid_entropy_length")
    static let invalidFiveBitValue = Self(rawValue: "invalid_five_bit_value")
    static let invalidIterationCount = Self(rawValue: "invalid_iteration_count")
    static let invalidMaximumDecodedByteCount = Self(
        rawValue: "invalid_maximum_decoded_byte_count"
    )
    static let invalidNonce = Self(rawValue: "invalid_nonce")
    static let invalidNonceLength = Self(rawValue: "invalid_nonce_length")
    static let invalidNoncePoint = Self(rawValue: "invalid_nonce_point")
    static let invalidNoncePointLength = Self(rawValue: "invalid_nonce_point_length")
    static let invalidNoncePointPrefix = Self(rawValue: "invalid_nonce_point_prefix")
    static let invalidPaddedPlaintextLength = Self(rawValue: "invalid_padded_plaintext_length")
    static let invalidParentFingerprintLength = Self(rawValue: "invalid_parent_fingerprint_length")
    static let invalidPayloadLength = Self(rawValue: "invalid_payload_length")
    static let invalidPrivateKey = Self(rawValue: "invalid_private_key")
    static let invalidPrivateKeyLength = Self(rawValue: "invalid_private_key_length")
    static let invalidPublicKey = Self(rawValue: "invalid_public_key")
    static let invalidPublicKeyLength = Self(rawValue: "invalid_public_key_length")
    static let invalidPublicKeyPrefix = Self(rawValue: "invalid_public_key_prefix")
    static let invalidRequestLength = Self(rawValue: "invalid_request_length")
    static let invalidRequestScalar = Self(rawValue: "invalid_request_scalar")
    static let invalidResponseLength = Self(rawValue: "invalid_response_length")
    static let invalidResponseScalar = Self(rawValue: "invalid_response_scalar")
    static let invalidSeedLength = Self(rawValue: "invalid_seed_length")
    static let invalidSignature = Self(rawValue: "invalid_signature")
    static let invalidSignatureLength = Self(rawValue: "invalid_signature_length")
    static let invalidSymmetricKeyLength = Self(rawValue: "invalid_symmetric_key_length")
    static let invalidTweak = Self(rawValue: "invalid_tweak")
    static let invalidTweakLength = Self(rawValue: "invalid_tweak_length")
    static let invalidVersion = Self(rawValue: "invalid_version")
    static let invalidWord = Self(rawValue: "invalid_word")
    static let invalidWordCount = Self(rawValue: "invalid_word_count")
    static let invalidWordList = Self(rawValue: "invalid_word_list")
    static let messageTooLong = Self(rawValue: "message_too_long")
    static let metalAllocationFailed = Self(rawValue: "metal_allocation_failed")
    static let metalCommandFailed = Self(rawValue: "metal_command_failed")
    static let metalInvalidOutput = Self(rawValue: "metal_invalid_output")
    static let metalPipelineInitializationFailed = Self(rawValue: "metal_pipeline_initialization_failed")
    static let metalResourceMissing = Self(rawValue: "metal_resource_missing")
    static let metalUnavailable = Self(rawValue: "metal_unavailable")
    static let mismatchedSetup = Self(rawValue: "mismatched_setup")
    static let nonceAlreadyUsed = Self(rawValue: "nonce_already_used")
    static let nonCanonicalDER = Self(rawValue: "non_canonical_der")
    static let paddedPlaintextLengthMustBeMultipleOf16 = Self(rawValue: "padded_plaintext_length_must_be_multiple_of_16")
    static let payloadLengthExceedsMaximum = Self(
        rawValue: "payload_length_exceeds_maximum"
    )
    static let phraseByteCountExceedsMaximum = Self(
        rawValue: "phrase_byte_count_exceeds_maximum"
    )
    static let randomGenerationFailed = Self(rawValue: "random_generation_failed")
    static let verificationFailed = Self(rawValue: "verification_failed")
    static let workBudgetExceeded = Self(rawValue: "work_budget_exceeded")
    static let workUnitCountOverflow = Self(rawValue: "work_unit_count_overflow")
    static let wordByteCountExceedsMaximum = Self(
        rawValue: "word_byte_count_exceeds_maximum"
    )
    static let wordCountExceedsMaximum = Self(rawValue: "word_count_exceeds_maximum")
    static let wordListResourceMissing = Self(rawValue: "word_list_resource_missing")
}
