// OpalDiagnostics.Event~OpalCrypto.swift

import OpalDiagnostics

extension OpalDiagnostics.Event {
    static let ecdsaSignBegin = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.ecdsa.sign.begin")
    static let ecdsaSignSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.ecdsa.sign.succeeded")
    static let ecdsaSignFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.ecdsa.sign.failed")
    static let ecdsaVerifyBegin = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.ecdsa.verify.begin")
    static let ecdsaVerifySucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.ecdsa.verify.succeeded")
    static let ecdsaVerifyFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.ecdsa.verify.failed")
    static let schnorrSignBegin = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.schnorr.sign.begin")
    static let schnorrSignSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.schnorr.sign.succeeded")
    static let schnorrSignFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.schnorr.sign.failed")
    static let schnorrVerifyBegin = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.schnorr.verify.begin")
    static let schnorrVerifySucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.schnorr.verify.succeeded")
    static let schnorrVerifyFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.schnorr.verify.failed")
    static let schnorrBatchVerifyBegin = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.schnorr.batch_verify.begin")
    static let schnorrBatchVerifySucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.schnorr.batch_verify.succeeded")
    static let schnorrBatchVerifyFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.schnorr.batch_verify.failed")
    static let schnorrBatchVerifyFallback = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.schnorr.batch_verify.fallback")
    static let verificationKeyDeriveSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.verification_key.derive.succeeded")
    static let verificationKeyDeriveFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.verification_key.derive.failed")
    static let verificationKeyParseSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.verification_key.parse.succeeded")
    static let verificationKeyParseFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.signature.verification_key.parse.failed")

    static let privateKeyGenerateSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.private.generate.succeeded")
    static let privateKeyGenerateFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.private.generate.failed")
    static let privateKeyParseSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.private.parse.succeeded")
    static let privateKeyParseFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.private.parse.failed")
    static let privateKeyTweakAddSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.private.tweak_add.succeeded")
    static let privateKeyTweakAddFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.private.tweak_add.failed")
    static let publicKeyParseSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.public.parse.succeeded")
    static let publicKeyParseFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.public.parse.failed")
    static let publicKeyDeriveSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.public.derive.succeeded")
    static let publicKeyDeriveFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.public.derive.failed")
    static let publicKeysDeriveSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.public.batch_derive.succeeded")
    static let publicKeysDeriveFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.public.batch_derive.failed")
    static let publicKeyTweakAddSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.public.tweak_add.succeeded")
    static let publicKeyTweakAddFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.public.tweak_add.failed")
    static let sharedSecretDeriveSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.shared_secret.derive.succeeded")
    static let sharedSecretDeriveFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.shared_secret.derive.failed")
    static let sharedSecretsDeriveSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.shared_secret.batch_derive.succeeded")
    static let sharedSecretsDeriveFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.shared_secret.batch_derive.failed")
    static let sharedSecretParseSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.shared_secret.parse.succeeded")
    static let sharedSecretParseFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.shared_secret.parse.failed")
    static let sharedPointXDeriveSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.shared_point_x.derive.succeeded")
    static let wifParseSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.wif.parse.succeeded")
    static let wifParseFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.wif.parse.failed")
    static let wifSerializeSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.wif.serialize.succeeded")
    static let wifSerializeFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.wif.serialize.failed")
    static let mnemonicParseSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.mnemonic.parse.succeeded")
    static let mnemonicParseFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.mnemonic.parse.failed")
    static let mnemonicGenerateSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.mnemonic.generate.succeeded")
    static let mnemonicGenerateFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.mnemonic.generate.failed")
    static let mnemonicSeedDeriveSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.mnemonic.seed.derive.succeeded")
    static let mnemonicSeedDeriveFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.mnemonic.seed.derive.failed")
    static let extendedPrivateParseSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.extended_private.parse.succeeded")
    static let extendedPrivateParseFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.extended_private.parse.failed")
    static let extendedPrivateRootSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.extended_private.root.succeeded")
    static let extendedPrivateRootFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.extended_private.root.failed")
    static let extendedPublicParseSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key.extended_public.parse.succeeded")
    static let extendedPublicParseFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key.extended_public.parse.failed")

    static let pbkdf2DeriveSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key_derivation.pbkdf2.derive.succeeded")
    static let pbkdf2DeriveFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key_derivation.pbkdf2.derive.failed")
    static let hkdfSHA256DeriveSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.key_derivation.hkdf_sha256.derive.succeeded")
    static let hkdfSHA256DeriveFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.key_derivation.hkdf_sha256.derive.failed")

    static let communicationEncryptBegin = OpalDiagnostics.Event(rawValue: "opalcrypto.communication.encrypt.begin")
    static let communicationEncryptSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.communication.encrypt.succeeded")
    static let communicationEncryptFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.communication.encrypt.failed")
    static let communicationDecryptBegin = OpalDiagnostics.Event(rawValue: "opalcrypto.communication.decrypt.begin")
    static let communicationDecryptSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.communication.decrypt.succeeded")
    static let communicationDecryptFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.communication.decrypt.failed")
    static let communicationCiphertextParseSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.communication.ciphertext.parse.succeeded")
    static let communicationCiphertextParseFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.communication.ciphertext.parse.failed")
    static let communicationSymmetricKeyParseSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.communication.symmetric_key.parse.succeeded")
    static let communicationSymmetricKeyParseFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.communication.symmetric_key.parse.failed")

    static let blindSignatureRequestBegin = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.request.begin")
    static let blindSignatureRequestSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.request.succeeded")
    static let blindSignatureRequestFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.request.failed")
    static let blindSignatureSignerPrepareSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.signer.prepare.succeeded")
    static let blindSignatureSignerPrepareFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.signer.prepare.failed")
    static let blindSignatureSignBegin = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.sign.begin")
    static let blindSignatureSignSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.sign.succeeded")
    static let blindSignatureSignFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.sign.failed")
    static let blindSignatureUnblindBegin = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.unblind.begin")
    static let blindSignatureUnblindSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.unblind.succeeded")
    static let blindSignatureUnblindFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.unblind.failed")
    static let blindSignatureVerifySucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.verify.succeeded")
    static let blindSignatureVerifyFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.blind_signature.verify.failed")

    static let pedersenSetupSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.pedersen.setup.succeeded")
    static let pedersenSetupFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.pedersen.setup.failed")
    static let pedersenCommitSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.pedersen.commit.succeeded")
    static let pedersenCommitFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.pedersen.commit.failed")
    static let pedersenVerifySucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.pedersen.verify.succeeded")
    static let pedersenVerifyFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.pedersen.verify.failed")
    static let pedersenCombineSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.pedersen.combine.succeeded")
    static let pedersenCombineFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.pedersen.combine.failed")
    static let pedersenCommitmentParseSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.pedersen.commitment.parse.succeeded")
    static let pedersenCommitmentParseFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.pedersen.commitment.parse.failed")
    static let pedersenNonceParseSucceeded = OpalDiagnostics.Event(rawValue: "opalcrypto.pedersen.nonce.parse.succeeded")
    static let pedersenNonceParseFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.pedersen.nonce.parse.failed")

    static let sha256Succeeded = OpalDiagnostics.Event(rawValue: "opalcrypto.hashing.sha256.succeeded")
    static let hash256Succeeded = OpalDiagnostics.Event(rawValue: "opalcrypto.hashing.hash256.succeeded")
    static let hash160Succeeded = OpalDiagnostics.Event(rawValue: "opalcrypto.hashing.hash160.succeeded")
    static let hmacSHA512Succeeded = OpalDiagnostics.Event(rawValue: "opalcrypto.hashing.hmac_sha512.succeeded")
    static let hmacSHA256Succeeded = OpalDiagnostics.Event(rawValue: "opalcrypto.hashing.hmac_sha256.succeeded")

    static let base58DecodeFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.encoding.base58.decode.failed")
    static let base58CheckDecodeFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.encoding.base58check.decode.failed")
    static let base32DecodeFailed = OpalDiagnostics.Event(rawValue: "opalcrypto.encoding.base32.decode.failed")
}
