// OpalCrypto+RSABSSA.swift

extension OpalCrypto {
    /// RSA blind signatures with appendix using the bounded RFC 9474 profile.
    ///
    /// The supported profile is RSA-2048 with SHA-384, MGF1-SHA384, a 48-byte
    /// PSS salt, and randomized message preparation. Signing keys generated by
    /// this namespace are opaque and intended for one RSABSSA attempt only.
    public enum RSABSSA {}
}
