// OpalCrypto.Signature+SchnorrNoncePolicy.swift

import Foundation

extension OpalCrypto.Signature {
    public enum SchnorrNoncePolicy: Sendable, Equatable {
        /// The Bitcoin Cash deterministic nonce derivation.
        case bchDeterministic

        /// The legacy deterministic nonce derivation previously exposed under
        /// a BIP-340 name.
        @available(
            *,
            deprecated,
            message: "Use .bchDeterministic for Bitcoin Cash Schnorr signing. This case preserves the legacy SHA-256(privateKey || digest) derivation and is not BIP-340."
        )
        case bip340Deterministic

        /// A nonce generated by the system cryptographic random-number generator.
        case random
    }
}
